name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true       # pulls theme submodules
          fetch-depth: 0         # required for .GitInfo/.Lastmod

      - name: Set Hugo version
        run: echo "HUGO_VERSION=0.134.0" >> $GITHUB_ENV  # pin as needed

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true
        # action installs Hugo fast; supports extended builds. :contentReference[oaicite:1]{index=1}

      - name: Compute baseURL
        id: baseurl
        run: |
          owner="${GITHUB_REPOSITORY_OWNER}"
          repo="${GITHUB_REPOSITORY#*/}"
          echo "url=https://myblogjourney.com" >> $GITHUB_OUTPUT

      - name: Build
        run: hugo --minify --baseURL "${{ steps.baseurl.outputs.url }}"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
        # official action that packages the site for Pages deploy. :contentReference[oaicite:2]{index=2}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # official Pages deploy action. :contentReference[oaicite:3]{index=3}
 
